name: Purge Cloudflare Cache After Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  purge_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
